version: '3.8'
services:
  redis:
    image: redis:7
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./redis-data:/data
    command: >
      redis-server
      --appendonly yes
      --appendfsync everysec
      --appendfilename "appendonly.aof"
      --dir /data
      --maxmemory 256mb
      --maxmemory-policy allkeys-lru
      --tcp-keepalive 60