version: '3.8'  
services:  
  redis:  
    image: redis:7  
    container_name: redis  
    restart: always  
    volumes:  
      - ./redis-data:/data  
    command: >  
      redis-server  
      --appendonly yes  
      --appendfsync everysec  
      --appendfilename "appendonly.aof"  
      --dir /data  
      --maxmemory 256mb  
      --maxmemory-policy allkeys-lru  
      --tcp-keepalive 60  
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 2m
      timeout: 5s
      retries: 2
      start_period: 30s
  mysql:  
    image: mysql:8  
    container_name: mysql  
    restart: always  
    volumes:  
      - ./mysql-data:/var/lib/mysql  
    environment:  
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    command: >  
      mysqld  
      --character-set-server=utf8mb4  
      --collation-server=utf8mb4_unicode_ci  
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "mysql -uroot -p$MYSQL_PASSWORD -e 'SELECT 1;' &&
          mysql -uroot -p$MYSQL_PASSWORD -e 'USE $MYSQL_DATABASE;'"
        ]
      interval: 10s
      timeout: 20s
      retries: 5
      start_period: 30s
  
  minio:  
    image: minio/minio  
    container_name: minio  
    command: server /data --console-address ":9001"  
    environment:  
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY}
    volumes:  
      - ./minio-data:/data  
  app:  
    image: nguyenvanan77/tech-device-shop:latest
    container_name: app  
    restart: always  
    ports:  
      - "8080:8080"  
    depends_on:  
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
      minio:
        condition: service_started
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -f http://localhost:8080/actuator/health"
        ]
      interval: 2m
      timeout: 20s
      retries: 3
      start_period: 30s
    environment:  
      # ===== SERVER =====  
      SERVER_PORT: 8080  
  
      # ===== MYSQL =====  
      MYSQL_HOST: mysql
      MYSQL_PORT: ${MYSQL_PORT}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USERNAME: ${MYSQL_USERNAME}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
  
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver  
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.MySQL8Dialect  
      SPRING_JPA_HIBERNATE_DDL_AUTO: update  
      SPRING_JPA_SHOW_SQL: true  
      SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL: true  
  
      # ===== REDIS =====  
      REDIS_HOST: redis
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
  
      SPRING_DATA_REDIS_HOST: redis  
      SPRING_DATA_REDIS_PORT: 6379  
      SPRING_DATA_REDIS_PASSWORD:
  
      # ===== JWT =====  
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      JWT_REFRESH_KEY: ${JWT_REFRESH_KEY}
      JWT_RESET_PASSWORD_KEY: ${JWT_RESET_PASSWORD_KEY}
      JWT_EXPIRY_DAY: ${JWT_EXPIRY_DAY}
      JWT_EXPIRY_HOUR: ${JWT_EXPIRY_HOUR}
      JWT_EXPIRY_MINUTE: ${JWT_EXPIRY_MINUTE}
      JWT_ISSUER: ${JWT_ISSUER}
  
      # ===== MINIO =====  
      MINIO_URL: http://minio:9000
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
      MINIO_BUCKET_IMAGES: ${MINIO_BUCKET_IMAGES}
      MINIO_BUCKET_VIDEOS: ${MINIO_BUCKET_VIDEO}
  
      # ===== FILE UPLOAD =====  
      SPRING_SERVLET_MULTIPART_MAX_FILE_SIZE: 200MB  
      SPRING_SERVLET_MULTIPART_MAX_REQUEST_SIZE: 200MB  
  
      # ===== OAUTH2 =====  
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}  
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET} 
      GOOGLE_REDIRECT_URI: ${GOOGLE_REDIRECT_URI} 
      GOOGLE_SCOPE: ${GOOGLE_SCOPE} 
  
      # ===== VNPAY ===== 
      VNPAY_TMN_CODE: ${VNPAY_TMN_CODE} 
      VNPAY_SECRET_KEY: ${VNPAY_SECRET_KEY} 
      VNPAY_PAY_URL: ${VNPAY_PAY_URL} 
      VNPAY_RETURN_URL: ${VNPAY_RETURN_URL} 
      VNPAY_IPN_URL: ${VNPAY_IPN_URL} 
 
      # ===== SENDGRID ===== 
      SENDGRID_API_KEY: ${SENDGRID_API_KEY} 
      SENDGRID_SENDER_EMAIL: ${SENDGRID_SENDER_EMAIL} 
      SENDGRID_SENDER_NAME: ${SENDGRID_SENDER_NAME} 
  
volumes:  
  redis-data:  
  mysql-data:  
  minio-data: