spring.application.name=TechDeviceShop

server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/ecommerce_db
spring.datasource.username=postgres
spring.datasource.password=160220057a
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto= update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret-key = 20340354f7e923dd7a453e552ab31d4cf6a0a60cb6d0fa173017541060ac2a9b
jwt.refresh-key = f2815bbc44f25db2c19affd86c27eb2e1eaa525333f836b60a75bea9b75e027f
jwt.reset-password-key = 33349a33a846f84e629533e4a540023ba04309a52f93d31add390da18abf9066
jwt.expiryHour = 1
jwt.expiryDay = 15

spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.password=
spring.data.redis.database=0

minio.url=http://localhost:9000
minio.accessKey=admin
minio.secretKey=admin123
minio.bucket.images=product-images
minio.bucket.videos=product-videos
spring.servlet.multipart.max-file-size=200MB
spring.servlet.multipart.max-request-size=200MB