-- =====================================
-- ADDRESSES
-- =====================================

CREATE TABLE addresses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    receiver_name VARCHAR(255),
    phone VARCHAR(20),
    province VARCHAR(100),
    district VARCHAR(100),
    ward VARCHAR(100),
    detail VARCHAR(255)
);


-- =====================================
-- USERS
-- =====================================

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255),
    full_name VARCHAR(255),
    phone VARCHAR(20),
    role VARCHAR(50),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    address_id BIGINT NOT NULL,
    is_deleted BOOLEAN DEFAULT FALSE,

    CONSTRAINT fk_users_address
        FOREIGN KEY (address_id)
        REFERENCES addresses(id)
        ON DELETE RESTRICT
);

CREATE INDEX idx_users_email ON users(email);
CREATE INDEX idx_users_role ON users(role);


-- =====================================
-- ROLES
-- =====================================

CREATE TABLE roles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) UNIQUE,
    password_hash VARCHAR(255),
    full_name VARCHAR(255),
    phone VARCHAR(20),
    role VARCHAR(50),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


-- =====================================
-- CATEGORIES
-- =====================================

CREATE TABLE categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255),
    slug VARCHAR(255) UNIQUE,
    parent_id BIGINT,
    is_deleted BOOLEAN DEFAULT FALSE,

    CONSTRAINT fk_categories_parent
        FOREIGN KEY (parent_id)
        REFERENCES categories(id)
        ON DELETE RESTRICT
);

CREATE INDEX idx_categories_parent ON categories(parent_id);
CREATE INDEX idx_categories_slug ON categories(slug);


-- =====================================
-- PRODUCTS
-- =====================================

CREATE TABLE products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255),
    business_id BIGINT,
    specifications JSONB,
    description TEXT,
    status VARCHAR(50),
    rating_avg DOUBLE PRECISION DEFAULT 0,
    review_count INT DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    is_deleted BOOLEAN DEFAULT FALSE,
    category_id BIGINT NOT NULL,

    CONSTRAINT fk_products_category
        FOREIGN KEY (category_id)
        REFERENCES categories(id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_products_business
        FOREIGN KEY (business_id)
        REFERENCES users(id)
        ON DELETE RESTRICT
);

CREATE INDEX idx_products_category ON products(category_id);
CREATE INDEX idx_products_business ON products(business_id);
CREATE INDEX idx_products_rating ON products(rating_avg DESC);
CREATE INDEX idx_products_created ON products(created_at DESC);


-- =====================================
-- PRODUCT ITEMS (SKU)
-- =====================================

CREATE TABLE product_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT,
    product_code VARCHAR(100) UNIQUE,
    original_price NUMERIC(12,2) NOT NULL,

    CONSTRAINT fk_product_items_product
        FOREIGN KEY (product_id)
        REFERENCES products(id)
        ON DELETE CASCADE
);

CREATE INDEX idx_product_items_product ON product_items(product_id);


-- =====================================
-- PRODUCT IMAGES
-- =====================================

CREATE TABLE product_images (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    image_url TEXT,
    is_main BOOLEAN DEFAULT FALSE,
    product_id BIGINT NOT NULL,

    CONSTRAINT fk_product_images_product
        FOREIGN KEY (product_id)
        REFERENCES products(id)
        ON DELETE CASCADE
);

CREATE INDEX idx_product_images_product ON product_images(product_id);


-- =====================================
-- PRODUCT VIDEOS
-- =====================================

CREATE TABLE product_videos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    video_url TEXT,
    is_main BOOLEAN DEFAULT FALSE,
    product_id BIGINT NOT NULL,

    CONSTRAINT fk_product_videos_product
        FOREIGN KEY (product_id)
        REFERENCES products(id)
        ON DELETE CASCADE
);


-- =====================================
-- CARTS
-- =====================================

CREATE TABLE carts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    user_id BIGINT UNIQUE NOT NULL,

    CONSTRAINT fk_carts_user
        FOREIGN KEY (user_id)
        REFERENCES users(id)
        ON DELETE CASCADE
);


-- =====================================
-- CART ITEMS
-- =====================================

CREATE TABLE cart_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    quantity INT NOT NULL CHECK (quantity > 0),
    cart_id BIGINT NOT NULL,
    product_item_id BIGINT NOT NULL,

    CONSTRAINT fk_cart_items_cart
        FOREIGN KEY (cart_id)
        REFERENCES carts(id)
        ON DELETE CASCADE,

    CONSTRAINT fk_cart_items_product_item
        FOREIGN KEY (product_item_id)
        REFERENCES product_items(id)
        ON DELETE RESTRICT
);

CREATE INDEX idx_cart_items_cart ON cart_items(cart_id);


-- =====================================
-- ORDERS
-- =====================================

CREATE TABLE orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    total_price NUMERIC(12,2),
    status VARCHAR(50),
    payment_method VARCHAR(50),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    user_id BIGINT NOT NULL,
    address_id BIGINT NOT NULL,

    CONSTRAINT fk_orders_user
        FOREIGN KEY (user_id)
        REFERENCES users(id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_orders_address
        FOREIGN KEY (address_id)
        REFERENCES addresses(id)
        ON DELETE RESTRICT
);

CREATE INDEX idx_orders_user ON orders(user_id);
CREATE INDEX idx_orders_created ON orders(created_at DESC);


-- =====================================
-- ORDER ITEMS
-- =====================================

CREATE TABLE order_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    quantity INT CHECK (quantity > 0),
    price NUMERIC(12,2),
    order_id BIGINT NOT NULL,
    product_item_id BIGINT NOT NULL,

    CONSTRAINT fk_order_items_order
        FOREIGN KEY (order_id)
        REFERENCES orders(id)
        ON DELETE CASCADE,

    CONSTRAINT fk_order_items_product_item
        FOREIGN KEY (product_item_id)
        REFERENCES product_items(id)
        ON DELETE RESTRICT
);

CREATE INDEX idx_order_items_order ON order_items(order_id);


-- =====================================
-- PAYMENTS
-- =====================================

CREATE TABLE payments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider VARCHAR(100),
    transaction_id VARCHAR(255),
    amount NUMERIC(12,2),
    status VARCHAR(50),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    order_id BIGINT UNIQUE NOT NULL,

    CONSTRAINT fk_payments_order
        FOREIGN KEY (order_id)
        REFERENCES orders(id)
        ON DELETE CASCADE
);


-- =====================================
-- REVIEWS
-- =====================================

CREATE TABLE reviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rating INT CHECK (rating BETWEEN 1 AND 5),
    comment TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    product_id BIGINT NOT NULL,
    user_id BIGINT,

    CONSTRAINT fk_reviews_user
        FOREIGN KEY (user_id)
        REFERENCES users(id)
        ON DELETE SET NULL,

    CONSTRAINT fk_reviews_product
        FOREIGN KEY (product_id)
        REFERENCES products(id)
        ON DELETE CASCADE,

    CONSTRAINT uq_user_product_review
        UNIQUE(user_id, product_id)
);

CREATE INDEX idx_reviews_product ON reviews(product_id);


-- =====================================
-- REVIEW IMAGES
-- =====================================

CREATE TABLE review_images (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    image_url TEXT,
    review_id BIGINT NOT NULL,

    CONSTRAINT fk_review_images_review
        FOREIGN KEY (review_id)
        REFERENCES reviews(id)
        ON DELETE CASCADE
);


-- =====================================
-- TOKEN
-- =====================================

CREATE TABLE token (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    access_token TEXT,
    refresh_token TEXT,
    user_id BIGINT UNIQUE NOT NULL,

    CONSTRAINT fk_token_user
        FOREIGN KEY (user_id)
        REFERENCES users(id)
        ON DELETE CASCADE
);


-- =====================================
-- EMAIL LOGS
-- =====================================

CREATE TABLE email_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255),
    subject VARCHAR(255),
    status VARCHAR(50),
    sent_at TIMESTAMP,
    user_id BIGINT,

    CONSTRAINT fk_email_logs_user
        FOREIGN KEY (user_id)
        REFERENCES users(id)
        ON DELETE SET NULL
);


-- =====================================
-- ATTRIBUTE TYPE
-- =====================================

CREATE TABLE attribute_type (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100)
);


-- =====================================
-- PRODUCT ATTRIBUTE MAPPING
-- =====================================

CREATE TABLE product_item_has_attribute_type (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_item_id BIGINT,
    attribute_type_id BIGINT,

    CONSTRAINT fk_pihat_product_item
        FOREIGN KEY (product_item_id)
        REFERENCES product_items(id)
        ON DELETE CASCADE,

    CONSTRAINT fk_pihat_attribute
        FOREIGN KEY (attribute_type_id)
        REFERENCES attribute_type(id)
        ON DELETE RESTRICT,

    CONSTRAINT uq_product_item_attr
        UNIQUE(product_item_id, attribute_type_id)
);


-- =====================================
-- PRODUCT OPTION
-- =====================================

CREATE TABLE product_option (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_item_has_attribute_type_id BIGINT,
    value_option VARCHAR(100),
    quantity_in_stock INT,

    CONSTRAINT fk_product_option_attr
        FOREIGN KEY (product_item_has_attribute_type_id)
        REFERENCES product_item_has_attribute_type(id)
        ON DELETE CASCADE,

    CONSTRAINT uq_option UNIQUE(product_item_has_attribute_type_id, value_option)
);


-- =====================================
-- SALES
-- =====================================

CREATE TABLE sales (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(100)
);


-- =====================================
-- PRODUCT SALE
-- =====================================

CREATE TABLE product_sale (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT,
    sale_id BIGINT,
    value INT,
    isActive BOOLEAN DEFAULT TRUE,

    CONSTRAINT fk_product_sale_product
        FOREIGN KEY (product_id)
        REFERENCES products(id)
        ON DELETE CASCADE,

    CONSTRAINT fk_product_sale_sale
        FOREIGN KEY (sale_id)
        REFERENCES sales(id)
        ON DELETE CASCADE
);

CREATE INDEX idx_product_sale_product ON product_sale(product_id);